# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Source1'
        db.create_table('mydata_source1', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user_id', self.gf('django.db.models.fields.related.ForeignKey')(db_column='user_id', on_delete=models.SET_NULL, to_field='username', to=orm['auth.User'], blank=True, null=True)),
            ('updated', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
            ('ExitQ1_AttribQuote', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ExitQ2_PhotoPermit', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ExitQ3_ClassReDo', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('ExitQ4_ExamPrep', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('ExitQ5_GroupStudy', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('ExitQ6_ExpectedGrade', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ExitQ7_EcoachFrequency', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ExitQ8_PrimaryUse', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('ExitQ9_GoodBadFeatures', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('ExitQ10_Misc', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('Exit_Q11_SurveyTimes', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('Post_Exam2_Feelings__1', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Post_Exam2_Feelings__2', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Post_Exam2_Feelings__3', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Post_Exam2_Feelings__4', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Post_Exam2_Feelings__5', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Post_Exam2_Feelings__6', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Exam_1_Satisfaction', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Exam_2_Satisfaction', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('PR_ProblemsTried_Exam2', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('PR_ProblemsTried_Exam1', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Message_3_Q1', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Reg_Enrolled', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Reg_GPA', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Reg_Gender', self.gf('django.db.models.fields.CharField')(max_length=5, null=True, blank=True)),
            ('Reg_Acad_Level', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('Signup_Opt_Out', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('ChemPrevious', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Math_Confidence', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass09', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('CHEM130HoursStudy', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('CHEM130OWLHours', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Mat_Textbook', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Mat_iClicker', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Mat_Calculator', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Exam_1_Score', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Exam_2_Score', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Final_Exam_Score', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('CHEM130Friends', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('APCourses', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('APCoursesTaken__Chemistry', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('APCoursesTaken__Biology', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('APCoursesTaken__Physics', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('APCoursesTaken__Math', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('APCoursesTaken__Other', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('CHEM130SLC', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('CHEM130Attendance', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('CHEM130DiscussionAttendance', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('CHEM130GoalGrade', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass26', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass27', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass28', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass29', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass30', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass31', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass38', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass39', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass40', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass42', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass43', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass44', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass45', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass48', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass47', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass49', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass50', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass46', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('GTD_01__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_02__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_03__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_04__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_05__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_06__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_07__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_08__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_09__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_10__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_11__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_12__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_13__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_14__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('GTD_15__done', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('YClass41', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass32', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass33', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass34', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass35', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass36', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass37', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass10', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass11', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass12', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass18', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass19', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass20', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass21', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass22', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass23', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass24', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass25', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass13', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass14', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass15', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass16', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass17', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass01', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass03', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass02', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass04', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass05', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass06', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass07', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('YClass08', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('CHEM130Reason__Possible_Concentrate_req', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('CHEM130Reason__Concentration_req', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('CHEM130Reason__Grad_req', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('CHEM130Reason__Credit', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('CHEM130Reason__Interest', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('CHEM130Confidence', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('CHEM130GradeConfidence', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('dist_ID', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('CHEM130Interest', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Message_2_Q1', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Message_2_Q2', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Message_2_Q3', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Quiz_Avg_Exam1', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Quiz_Avg_Exam2', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Quiz_Avg_Final', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Participation_Avg_Exam1', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Participation_Avg_Exam2', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Participation_Avg_Final', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('OWL_Avg_Exam1', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('OWL_Avg_Exam2', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('OWL_Avg_Final', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('zombi_group', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('zombi_1_write', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('zombi_2_write', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('zombi_2_review', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('zombi_3_write', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('zombi_3_review', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('zombi_3_rewrite', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('zombi_4_rewrite', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('PreExam2_Q1', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
        ))
        db.send_create_signal('mydata18', ['Source1'])

        # Adding model 'EmptySource'
        db.create_table('mydata18_emptysource', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user_id', self.gf('django.db.models.fields.related.ForeignKey')(db_column='user_id', on_delete=models.SET_NULL, to_field='username', to=orm['auth.User'], blank=True, null=True)),
            ('updated', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
        ))
        db.send_create_signal('mydata18', ['EmptySource'])

        # Adding model 'Common1'
        db.create_table('mydata_common1', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user_id', self.gf('django.db.models.fields.related.ForeignKey')(db_column='user_id', on_delete=models.SET_NULL, to_field='username', to=orm['auth.User'], blank=True, null=True)),
            ('updated', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
            ('First_Name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('Last_Name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('uniqname', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('Gender', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('BirthDay', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('BirthMo', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('BirthYr', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Semesters_Completed', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('College', self.gf('django.db.models.fields.CharField')(max_length=11, null=True, blank=True)),
            ('College_Other', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('Concentrate__Engineering', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Physics', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Chemistry', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Biology', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Biology_MCDB', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Biology_EEB', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Health', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Humanities', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Math', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Stats', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Neurosci', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Social_Science_not_Psych', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Psych_BBCS', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Education', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__IDK', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Other', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate_Other', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('Declared', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('Class_Standing', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('Cum_GPA_Survey', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Employment', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('Involved_In__Greek', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Sports', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Religious', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Research', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Volunteering', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Music_Art', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Other', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Other_Commitment', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('Post_College', self.gf('django.db.models.fields.CharField')(max_length=13, null=True, blank=True)),
            ('Parent_Ed', self.gf('django.db.models.fields.CharField')(max_length=14, null=True, blank=True)),
            ('High_School_CumGPA', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
        ))
        db.send_create_signal('mydata18', ['Common1'])


    def backwards(self, orm):
        # Deleting model 'Source1'
        db.delete_table('mydata_source1')

        # Deleting model 'EmptySource'
        db.delete_table('mydata18_emptysource')

        # Deleting model 'Common1'
        db.delete_table('mydata_common1')


    models = {
        'auth.group': {
            'Meta': {'object_name': 'Group'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        'auth.permission': {
            'Meta': {'ordering': "('content_type__app_label', 'content_type__model', 'codename')", 'unique_together': "(('content_type', 'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'mydata18.common1': {
            'BirthDay': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'BirthMo': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'BirthYr': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Class_Standing': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'College': ('django.db.models.fields.CharField', [], {'max_length': '11', 'null': 'True', 'blank': 'True'}),
            'College_Other': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'Concentrate_Other': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'Concentrate__Biology': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Biology_EEB': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Biology_MCDB': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Chemistry': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Education': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Engineering': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Health': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Humanities': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__IDK': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Math': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Neurosci': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Other': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Physics': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Psych_BBCS': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Social_Science_not_Psych': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Stats': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Cum_GPA_Survey': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Declared': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'Employment': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'First_Name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'Gender': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'High_School_CumGPA': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Greek': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Music_Art': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Other': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Religious': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Research': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Sports': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Volunteering': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Last_Name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'Meta': {'object_name': 'Common1', 'db_table': "'mydata_common1'"},
            'Other_Commitment': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'Parent_Ed': ('django.db.models.fields.CharField', [], {'max_length': '14', 'null': 'True', 'blank': 'True'}),
            'Post_College': ('django.db.models.fields.CharField', [], {'max_length': '13', 'null': 'True', 'blank': 'True'}),
            'Semesters_Completed': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'uniqname': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'user_id': ('django.db.models.fields.related.ForeignKey', [], {'db_column': "'user_id'", 'on_delete': 'models.SET_NULL', 'to_field': "'username'", 'to': "orm['auth.User']", 'blank': 'True', 'null': 'True'})
        },
        'mydata18.emptysource': {
            'Meta': {'object_name': 'EmptySource'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'user_id': ('django.db.models.fields.related.ForeignKey', [], {'db_column': "'user_id'", 'on_delete': 'models.SET_NULL', 'to_field': "'username'", 'to': "orm['auth.User']", 'blank': 'True', 'null': 'True'})
        },
        'mydata18.source1': {
            'APCourses': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'APCoursesTaken__Biology': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'APCoursesTaken__Chemistry': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'APCoursesTaken__Math': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'APCoursesTaken__Other': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'APCoursesTaken__Physics': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130Attendance': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130Confidence': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130DiscussionAttendance': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130Friends': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130GoalGrade': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130GradeConfidence': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130HoursStudy': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130Interest': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130OWLHours': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130Reason__Concentration_req': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130Reason__Credit': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130Reason__Grad_req': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130Reason__Interest': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130Reason__Possible_Concentrate_req': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'CHEM130SLC': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ChemPrevious': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Exam_1_Satisfaction': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Exam_1_Score': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Exam_2_Satisfaction': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Exam_2_Score': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ10_Misc': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ1_AttribQuote': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ2_PhotoPermit': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ3_ClassReDo': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ4_ExamPrep': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ5_GroupStudy': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ6_ExpectedGrade': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ7_EcoachFrequency': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ8_PrimaryUse': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'ExitQ9_GoodBadFeatures': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'Exit_Q11_SurveyTimes': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'Final_Exam_Score': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_01__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_02__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_03__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_04__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_05__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_06__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_07__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_08__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_09__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_10__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_11__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_12__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_13__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_14__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'GTD_15__done': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Mat_Calculator': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Mat_Textbook': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Mat_iClicker': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Math_Confidence': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Message_2_Q1': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Message_2_Q2': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Message_2_Q3': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Message_3_Q1': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Meta': {'object_name': 'Source1', 'db_table': "'mydata_source1'"},
            'OWL_Avg_Exam1': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'OWL_Avg_Exam2': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'OWL_Avg_Final': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'PR_ProblemsTried_Exam1': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'PR_ProblemsTried_Exam2': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Participation_Avg_Exam1': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Participation_Avg_Exam2': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Participation_Avg_Final': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Post_Exam2_Feelings__1': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Post_Exam2_Feelings__2': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Post_Exam2_Feelings__3': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Post_Exam2_Feelings__4': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Post_Exam2_Feelings__5': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Post_Exam2_Feelings__6': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'PreExam2_Q1': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Quiz_Avg_Exam1': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Quiz_Avg_Exam2': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Quiz_Avg_Final': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Reg_Acad_Level': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'Reg_Enrolled': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Reg_GPA': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Reg_Gender': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'Signup_Opt_Out': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass01': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass02': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass03': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass04': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass05': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass06': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass07': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass08': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass09': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass10': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass11': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass12': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass13': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass14': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass15': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass16': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass17': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass18': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass19': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass20': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass21': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass22': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass23': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass24': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass25': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass26': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass27': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass28': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass29': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass30': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass31': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass32': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass33': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass34': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass35': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass36': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass37': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass38': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass39': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass40': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass41': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass42': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass43': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass44': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass45': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass46': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass47': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass48': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass49': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'YClass50': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'dist_ID': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'user_id': ('django.db.models.fields.related.ForeignKey', [], {'db_column': "'user_id'", 'on_delete': 'models.SET_NULL', 'to_field': "'username'", 'to': "orm['auth.User']", 'blank': 'True', 'null': 'True'}),
            'zombi_1_write': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'zombi_2_review': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'zombi_2_write': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'zombi_3_review': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'zombi_3_rewrite': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'zombi_3_write': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'zombi_4_rewrite': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'zombi_group': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        }
    }

    complete_apps = ['mydata18']