# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Source1'
        db.create_table('mydata_source1', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user_id', self.gf('django.db.models.fields.related.ForeignKey')(db_column='user_id', on_delete=models.SET_NULL, to_field='username', to=orm['auth.User'], blank=True, null=True)),
            ('updated', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
            ('SLC_Enrolled', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('AP_Bio', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('AP_Chem', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('Confidence', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('Goal_Grade', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Reason__Possible_Concentrate_req', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Reason__Concentration_req', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Reason__Grad_req', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Reason__Credit', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Reason__Interest', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Subject_Interest', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('Attendance_Anticipated', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('FS_MostValuable__advice_students', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_MostValuable__advice_professors', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_MostValuable__study_tips', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_MostValuable__problem_roulette', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_MostValuable__video_content', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_MostValuable__grade_prediction_tool', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_MostValuable__grade_calculator', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_MostValuable__class_calendar', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_LeastValuable__advice_students', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_LeastValuable__advice_professors', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_LeastValuable__study_tips', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_LeastValuable__problem_roulette', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_LeastValuable__video_content', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_LeastValuable__grade_prediction_tool', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_LeastValuable__grade_calculator', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_LeastValuable__class_calendar', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('FS_Changes', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('FS_Usage', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('FS_Challenges', self.gf('django.db.models.fields.TextField')(null=True, blank=True)),
            ('Exam1_FR', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam1_MC', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam1_Score', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam1_ClassAvg', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam2_FR', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam2_MC', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam2_Score', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam2_ClassAvg', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam3_FR', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam3_MC', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam3_Score', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam3_ClassAvg', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam4_FR', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam4_MC', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam4_Score', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Exam4_ClassAvg', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Project1_Grade', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Project2_Grade', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Project3_Grade', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('iClicker_Grade', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('CellMap_Grade', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('Num_PR_Questions', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Grade_PR_Questions', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('MCDB310FinalGradeLetter', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('MCDB310FinalGradeNumber', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('dist_id', self.gf('django.db.models.fields.CharField')(max_length=50, null=True, blank=True)),
            ('Pred_MostProb_Initial', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Pred_MostProb_PostExam1', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Pred_MostProb_PostExam2', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Pred_MostProb_PostExam3', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
        ))
        db.send_create_signal('mydata6', ['Source1'])

        # Adding model 'EmptySource'
        db.create_table('mydata6_emptysource', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user_id', self.gf('django.db.models.fields.related.ForeignKey')(db_column='user_id', on_delete=models.SET_NULL, to_field='username', to=orm['auth.User'], blank=True, null=True)),
            ('updated', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
        ))
        db.send_create_signal('mydata6', ['EmptySource'])

        # Adding model 'Common1'
        db.create_table('mydata_common1', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('user_id', self.gf('django.db.models.fields.related.ForeignKey')(db_column='user_id', on_delete=models.SET_NULL, to_field='username', to=orm['auth.User'], blank=True, null=True)),
            ('updated', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
            ('First_Name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('Last_Name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('uniqname', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('Gender', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('BirthDay', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('BirthMo', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('BirthYr', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Semesters_Completed', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('College', self.gf('django.db.models.fields.CharField')(max_length=11, null=True, blank=True)),
            ('College_Other', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('Concentrate__Engineering', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Physics', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Chemistry', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Biology', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Biology_MCDB', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Biology_EEB', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Health', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Humanities', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Math', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Stats', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Neurosci', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Social_Science_not_Psych', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Psych_BBCS', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Education', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__IDK', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate__Other', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Concentrate_Other', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('Declared', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('Class_Standing', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('Cum_GPA_Survey', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('Employment', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('Involved_In__Greek', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Sports', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Religious', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Research', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Volunteering', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Music_Art', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Involved_In__Other', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('Other_Commitment', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('Post_College', self.gf('django.db.models.fields.CharField')(max_length=13, null=True, blank=True)),
            ('Parent_Ed', self.gf('django.db.models.fields.CharField')(max_length=14, null=True, blank=True)),
            ('High_School_CumGPA', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
        ))
        db.send_create_signal('mydata6', ['Common1'])


    def backwards(self, orm):
        # Deleting model 'Source1'
        db.delete_table('mydata_source1')

        # Deleting model 'EmptySource'
        db.delete_table('mydata6_emptysource')

        # Deleting model 'Common1'
        db.delete_table('mydata_common1')


    models = {
        'auth.group': {
            'Meta': {'object_name': 'Group'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        'auth.permission': {
            'Meta': {'ordering': "('content_type__app_label', 'content_type__model', 'codename')", 'unique_together': "(('content_type', 'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'mydata6.common1': {
            'BirthDay': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'BirthMo': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'BirthYr': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Class_Standing': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'College': ('django.db.models.fields.CharField', [], {'max_length': '11', 'null': 'True', 'blank': 'True'}),
            'College_Other': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'Concentrate_Other': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'Concentrate__Biology': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Biology_EEB': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Biology_MCDB': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Chemistry': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Education': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Engineering': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Health': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Humanities': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__IDK': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Math': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Neurosci': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Other': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Physics': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Psych_BBCS': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Social_Science_not_Psych': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Concentrate__Stats': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Cum_GPA_Survey': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Declared': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'Employment': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'First_Name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'Gender': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'High_School_CumGPA': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Greek': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Music_Art': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Other': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Religious': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Research': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Sports': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Involved_In__Volunteering': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Last_Name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'Meta': {'object_name': 'Common1', 'db_table': "'mydata_common1'"},
            'Other_Commitment': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'Parent_Ed': ('django.db.models.fields.CharField', [], {'max_length': '14', 'null': 'True', 'blank': 'True'}),
            'Post_College': ('django.db.models.fields.CharField', [], {'max_length': '13', 'null': 'True', 'blank': 'True'}),
            'Semesters_Completed': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'uniqname': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'user_id': ('django.db.models.fields.related.ForeignKey', [], {'db_column': "'user_id'", 'on_delete': 'models.SET_NULL', 'to_field': "'username'", 'to': "orm['auth.User']", 'blank': 'True', 'null': 'True'})
        },
        'mydata6.emptysource': {
            'Meta': {'object_name': 'EmptySource'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'user_id': ('django.db.models.fields.related.ForeignKey', [], {'db_column': "'user_id'", 'on_delete': 'models.SET_NULL', 'to_field': "'username'", 'to': "orm['auth.User']", 'blank': 'True', 'null': 'True'})
        },
        'mydata6.source1': {
            'AP_Bio': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'AP_Chem': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'Attendance_Anticipated': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'CellMap_Grade': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Confidence': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'Exam1_ClassAvg': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam1_FR': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam1_MC': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam1_Score': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam2_ClassAvg': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam2_FR': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam2_MC': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam2_Score': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam3_ClassAvg': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam3_FR': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam3_MC': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam3_Score': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam4_ClassAvg': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam4_FR': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam4_MC': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Exam4_Score': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'FS_Challenges': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'FS_Changes': ('django.db.models.fields.TextField', [], {'null': 'True', 'blank': 'True'}),
            'FS_LeastValuable__advice_professors': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_LeastValuable__advice_students': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_LeastValuable__class_calendar': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_LeastValuable__grade_calculator': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_LeastValuable__grade_prediction_tool': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_LeastValuable__problem_roulette': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_LeastValuable__study_tips': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_LeastValuable__video_content': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_MostValuable__advice_professors': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_MostValuable__advice_students': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_MostValuable__class_calendar': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_MostValuable__grade_calculator': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_MostValuable__grade_prediction_tool': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_MostValuable__problem_roulette': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_MostValuable__study_tips': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_MostValuable__video_content': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'FS_Usage': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'Goal_Grade': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Grade_PR_Questions': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'MCDB310FinalGradeLetter': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'MCDB310FinalGradeNumber': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Meta': {'object_name': 'Source1', 'db_table': "'mydata_source1'"},
            'Num_PR_Questions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Pred_MostProb_Initial': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Pred_MostProb_PostExam1': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Pred_MostProb_PostExam2': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Pred_MostProb_PostExam3': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'Project1_Grade': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Project2_Grade': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Project3_Grade': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'Reason__Concentration_req': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Reason__Credit': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Reason__Grad_req': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Reason__Interest': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'Reason__Possible_Concentrate_req': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'SLC_Enrolled': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'Subject_Interest': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'dist_id': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'iClicker_Grade': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'updated': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'user_id': ('django.db.models.fields.related.ForeignKey', [], {'db_column': "'user_id'", 'on_delete': 'models.SET_NULL', 'to_field': "'username'", 'to': "orm['auth.User']", 'blank': 'True', 'null': 'True'})
        }
    }

    complete_apps = ['mydata6']